### ISSUE TITLE
is there a way to implement REST path parameters?

### ISSUE THREAD

**Issue by imranansari** [ldez/ghwebhook#1]
I'm curious if you can point to me in the right direction for implementing path parameters like below :
```go
ghw.WithPath("/web-hook/app1")
```
I'm implementing a webhook service that will be used with multiple apps, and wanted to pass the `appname` as a path parameter to the webhook.
The webhook path will be '/web-hook'

thanks for sharing this code!

**Comment by ldez** [comment]
Could you explain me what do you want do with the `appname`?

I can implement a PathPrefix system to allow queries `/web-hook/app1` to be handle by a webhook on `/web-hook`

**Comment by imranansari** [comment]
the webhook service I'm writing is configurable by a consul persisted JSON for different automation use-cases , so would like to do something like below.

```go
...
ghw.WithPath("/web-hook/{appName}"),
...
```
Then in the event handler if I can access the `appName`, I can do :
```go
c = consul..GetConfig(appName)
doAutomationTasks(payload, c)
```

**Comment by ldez** [comment]
Ok I understand your point, I think I can do something.

**Comment by ldez** [comment]
You can now use regex as path:

```go
ghw.WithPath("/web-hook/(.+)"),
```

For now it's not possible to use the "appname" inside handlers, but I'm working on this.

**Comment by imranansari** [comment]
Awesome! thanks @ldez

**Comment by ldez** [comment]
I created a new version, now you can do that:

```go
package main

import (
	"log"
	"net/url"
	"regexp"

	"github.com/google/go-github/github"
	ghw "github.com/ldez/ghwebhook"
	"github.com/ldez/ghwebhook/eventtype"
)

func main() {
	path := "/web-hook/(.+)"
	exp := regexp.MustCompile(path)

	eventHandlers := ghw.NewEventHandlers().
		OnIssues(func(uri *url.URL, payload *github.WebHookPayload, event *github.IssuesEvent) {
			appName := exp.FindStringSubmatch(uri.Path)
			log.Println(appName[1], event.GetAction(), event.Issue)
		}).
		OnPullRequest(func(uri *url.URL, payload *github.WebHookPayload, event *github.PullRequestEvent) {
			appName := exp.FindStringSubmatch(uri.Path)
			log.Println(appName[1], event.GetAction(), event.GetNumber())
		}).
		OnPing(func(uri *url.URL, payload *github.WebHookPayload, event *github.PingEvent) {
			appName := exp.FindStringSubmatch(uri.Path)
			log.Println(appName[1], event.GetHookID(), event.GetZen())
		})

	webhook := ghw.NewWebHook(
		eventHandlers,
		ghw.WithPort(5000),
		ghw.WithPath(path),
		ghw.Debug,
		ghw.WithEventTypes(eventtype.Issues, eventtype.PullRequest, eventtype.Ping))

	err := webhook.ListenAndServe()
	if err != nil {
		log.Fatal(err)
	}
}

```

**Comment by imranansari** [comment]
looks great! will kick the tires as soon as I get back from vacation and provide feedback. 
Appreciate your time.

**Comment by ldez** [comment]
Any news?

**Comment by imranansari** [comment]
Sorry for the delayed response, this LGTM.
thanks again!
